/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as Lang404RouteImport } from './routes/$lang/404'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangGuideRouteImport } from './routes/$lang/guide'
import { Route as LangRulesRouteImport } from './routes/$lang/rules'
import { Route as LangTournamentRouteImport } from './routes/$lang/tournament'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const Lang404Route = Lang404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangGuideRoute = LangGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => LangRoute,
} as any)
const LangRulesRoute = LangRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => LangRoute,
} as any)
const LangTournamentRoute = LangTournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/404': typeof Lang404Route
  '/$lang/contact': typeof LangContactRoute
  '/$lang/guide': typeof LangGuideRoute
  '/$lang/rules': typeof LangRulesRoute
  '/$lang/tournament': typeof LangTournamentRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/404': typeof Lang404Route
  '/$lang/contact': typeof LangContactRoute
  '/$lang/guide': typeof LangGuideRoute
  '/$lang/rules': typeof LangRulesRoute
  '/$lang/tournament': typeof LangTournamentRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/404': typeof Lang404Route
  '/$lang/contact': typeof LangContactRoute
  '/$lang/guide': typeof LangGuideRoute
  '/$lang/rules': typeof LangRulesRoute
  '/$lang/tournament': typeof LangTournamentRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/404'
    | '/$lang/contact'
    | '/$lang/guide'
    | '/$lang/rules'
    | '/$lang/tournament'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/404'
    | '/$lang/contact'
    | '/$lang/guide'
    | '/$lang/rules'
    | '/$lang/tournament'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/404'
    | '/$lang/contact'
    | '/$lang/guide'
    | '/$lang/rules'
    | '/$lang/tournament'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/404': {
      id: '/$lang/404'
      path: '/404'
      fullPath: '/$lang/404'
      preLoaderRoute: typeof Lang404RouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/guide': {
      id: '/$lang/guide'
      path: '/guide'
      fullPath: '/$lang/guide'
      preLoaderRoute: typeof LangGuideRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/rules': {
      id: '/$lang/rules'
      path: '/rules'
      fullPath: '/$lang/rules'
      preLoaderRoute: typeof LangRulesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/tournament': {
      id: '/$lang/tournament'
      path: '/tournament'
      fullPath: '/$lang/tournament'
      preLoaderRoute: typeof LangTournamentRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  Lang404Route: typeof Lang404Route
  LangContactRoute: typeof LangContactRoute
  LangGuideRoute: typeof LangGuideRoute
  LangRulesRoute: typeof LangRulesRoute
  LangTournamentRoute: typeof LangTournamentRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  Lang404Route: Lang404Route,
  LangContactRoute: LangContactRoute,
  LangGuideRoute: LangGuideRoute,
  LangRulesRoute: LangRulesRoute,
  LangTournamentRoute: LangTournamentRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
